apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        - name: GIT_REPO
          value: {{ .Values.gitRepo }}
        - name: GIT_USERNAME
          valueFrom:
              secretKeyRef:
                name: {{ .Values.gitSecretName }}
                key: {{ .Values.gitUsernameSecretKey }}
        - name: GIT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: {{ .Values.gitSecretName }}
                key: {{ .Values.gitPasswordSecretKey }}
        - name: GIT_TYPE
          value:  {{ .Values.gitType }}
