kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.serviceName }}
  labels:
   app: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.serviceName }}
  ports:
  - protocol: "TCP"
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}
  type: ClusterIP
